version: '2'
services:
      hugo-homepage:
          build: .
          image: hugo_shamuel:latest
          hostname: hugo-homepage
          container_name: hugo-homepage
          logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"
          # ports:
          #     - "1313:1313"
          volumes:
              - ../landing-page-shamuel:/shamuel.com/themes/landing-page-shamuel
              - ./conf/landing.config.toml:/shamuel.com/config.toml:ro
              - ../shamuel.com:/shamuel.com/public
          environment:
              - TZ=Europe/Moscow
              - HUGO_VERSION=
              - SITE_NAME=shamuel.com
              - SITE_THEME=landing-page-shamuel
      hugo-blog:
          build: .
          image: hugo_shamuel:latest
          hostname: hugo-blog
          container_name: hugo-blog
          logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"
          # ports:
          #     - "1313:1313"
          volumes:
              - ../blog-shamuel:/blog.shamuel.com/themes/blog-shamuel
              - ./conf/blog.config.toml:/blog.shamuel.com/config.toml:ro
              - ../blog.shamuel.com:/blog.shamuel.com/public
              - ../blog-content:/blog.shamuel.com/content
          environment:
              - TZ=Europe/Moscow
              - HUGO_VERSION=
              - SITE_NAME=blog.shamuel.com
              - SITE_THEME=blog-shamuel
      nginx-web:
          build: ../shamuel-nginx
          image: shamuel-nginx:latest
          hostname: nginx-web
          restart: always
          container_name: nginx-web
          logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"
          ports:
              - "80:80"
              - "443:443"
          volumes:
              #- /usr/share/nginx/html/shamuel.com:/usr/share/nginx/html/shamuel.com:ro
              #- /usr/share/nginx/html/blog.shamuel.com:/usr/share/nginx/html/blog.shamuel.com:ro
              - ../shamuel.com:/usr/share/nginx/html/shamuel.com
              - ../blog.shamuel.com:/usr/share/nginx/html/blog.shamuel.com
              - ../ssl:/etc/nginx/ssl/
          environment:
              - AWS_REGION=
              - AWS_ACCESS_KEY_ID=
              - AWS_SECRET_ACCESS_KEY=
              - LETSENCRYPT=false
              - EXISTCERTS=true
              - EMAIL=theshamuel@gmail.com
              - DOMAIN=shamuel.com