version: '2'
services:
      hugo:
          build: .
          image: hugo_shamuel:latest
          hostname: hugo
          restart: always
          container_name: hugo
          network_mode: bridge
          logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"
          # ports:
          #     - "1313:1313"
          volumes:
              - /landing-page-shamuel:/shamuel.com/themes/landing-page-shamuel
              - ./conf/config.toml:/shamuel.com/config.toml:ro
              - /usr/share/nginx/html:/shamuel.com/public
          environment:
              - TZ=Europe/Moscow
              - HUGO_VERSION=0.31.1
              - SITE_NAME=shamuel.com
              - SITE_THEME=landing-page-shamuel
networks:
  default:
    external:
      name: bridge
