version: '2'
services:
      hugo:
          build: .
          image: hugo_shamuel:latest
          hostname: hugo
          restart: always
          container_name: hugo
          network_mode: bridge
          logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"
          # ports:
          #     - "1313:1313"
          volumes:
              - /landing-page-shamuel:/shamuel.com/themes/<ex.com.theme>
              - ./conf/config.toml:/shamuel.com/config.toml:ro
              - /usr/share/nginx/html:/shamuel.com/public
          environment:
              - TZ=Europe/Moscow
              - HUGO_VERSION=0.31.1
              - SITE_NAME=shamuel.com
              - SITE_THEME=<ex.com.theme>

      nginx-lp:
          image: theshamuel/nginx-lelego:latest
          hostname: nginx-lp
          restart: always
          container_name: nginx-lp
          network_mode: bridge
          logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"
          ports:
              - "80:80"
              - "443:443"
          volumes:
              - /usr/share/nginx/html:/usr/share/nginx/html
          environment:
              - EMAIL=theshamuel@gmail.com>
              - DOMAIN=shamuel.com
networks:
  default:
    external:
      name: bridge
