version: '2'
services:
      hugo-hp:
          build: .
          image: hugo_shamuel:latest
          hostname: hugo-hp
          container_name: hugo-hp
          logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"
          # ports:
          #     - "1313:1313"
          volumes:
              - ../landing-page-shamuel:/shamuel.com/themes/landing-page-shamuel
              - ./conf/landing.config.toml:/shamuel.com/themes/config.toml:ro
              - ../shamuel.com:/shamuel.com/public
          environment:
              - TZ=Europe/Moscow
              - HUGO_VERSION=0.46
              - SITE_NAME=shamuel.com
              - SITE_THEME=landing-page-shamuel
      hugo-blog:
          build: .
          image: hugo_shamuel:latest
          hostname: hugo-blog
          container_name: hugo-blog
          logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"
          # ports:
          #     - "1313:1313"
          volumes:
              - ../blog-shamuel:/blog.shamuel.com/themes/blog-shamuel
              - ./conf/blog.config.toml:/blog.shamuel.com/themes/config.toml:ro
              - ../blog.shamuel.com:/blog.shamuel.com/public
          environment:
              - TZ=Europe/Moscow
              - HUGO_VERSION=0.46
              - SITE_NAME=blog.shamuel.com
              - SITE_THEME=blog-shamuel
      nginx-lp:
          build: ../shamuel-nginx
          image: shamuel-nginx:latest
          hostname: nginx-lp
          restart: always
          container_name: nginx-lp
          logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"
          ports:
              - "80:80"
              - "443:443"
          volumes:
              #- /usr/share/nginx/html/shamuel.com:/usr/share/nginx/html/shamuel.com:ro
              #- /usr/share/nginx/html/blog.shamuel.com:/usr/share/nginx/html/blog.shamuel.com:ro
              - ../shamuel.com:/usr/share/nginx/html/shamuel.com:ro
              - ../blog.shamuel.com:/usr/share/nginx/html/blog.shamuel.com:ro
              - ../ssl:/etc/nginx/
          environment:
              - AWS_REGION=
              - AWS_ACCESS_KEY_ID=
              - AWS_SECRET_ACCESS_KEY=
              - LETSENCRYPT=false
              - EMAIL=theshamuel@gmail.com
              - DOMAIN=shamuel.com