version: '2'
services:
      hugo:
          build: .
          image: hugo_shamuel:latest
          hostname: hugo
          restart: always
          container_name: hugo

          logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"
          ports:
              - "1313:1313"
          environment:
              - TZ=Europe/Moscow
