baseurl = "https://blog.shamuel.com"
languageCode = "en-us"
title = "Blog of @theshamuel"
theme = "blog-shamuel"
Paginate = 10

[params]
  twitterName = "theshamuel"
  githubName = "theshamuel"
  linkedinName = "alex-gladkikh-767a15115"
  #description = ""
  #google_analytics = "UA-xxxxxx-xx"