## Basic Configuration
baseurl = "https://blog.shamuel.com/"
languageCode = "en"

theme = "blog-shamuel"

## Site Settings
[params]
    author = "@theshamuel"
    title = "theshamuel"
    description = "Просто блог"
    authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    # please choose either GraphComment or Disqus

## Social Accounts
[params.social]
    github = "theshamuel"
    xing = "Alex_Gladkikh"
    linkedin = "alex-gladkikh-767a15115"
    twitter = "theshamuel"
    facebook = "100013211986136"
    email = "theshamuel@gmail.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
