## Basic Configuration
baseurl = "https://blog.shamuel.com/"
languageCode = "en"
title = "Blog of @theshamuel"
theme = "blog-shamuel"
enableRobotsTXT=true
canonifyURLs=true
googleAnalytics="UA-123954998-1"
disqusShortname = "blog-shamuel-com"

## Site Settings
[params]
    author = "@theshamuel"
    title = "theshamuel"
    description = "Заметки на технические темы и не только"
    authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"

## Social Accounts
[params.social]
    github = "theshamuel"
    xing = "Alex_Gladkikh"
    linkedin = "alex-gladkikh-767a15115"
    twitter = "theshamuel"
    facebook = "100013211986136"
    email = "theshamuel@gmail.com"

## Main Menu
[[menu.main]]
    name = "Домой"
    weight = 100
    identifier = ""
    url = "/"
[[menu.main]]
    name = "О себе"
    identifier = ""
    weight = 300
    url = "http://shamuel.com"
